# Dependencies - "fenced_code_blocks" is automatically enabled
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "tables", "with_toc_data"]
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: SHML
tagline: '$(shell markup language)'
description: 'SHML is a shell framework for faster and easier script development.'
url: https://github.com/odb/shml/
baseurl: /shml/

# paginate: 1

# Custom vars
version: 1.0.4
